### ISSUE TITLE
IoT Gateway

### ISSUE THREAD

**Issue by mikelovic** [LibreSolar/thingset#1]
@martinjaeger : hello martin. @ben-talla is from Dakar and he is interested in collaboration for the development.
Can you draft your thinkings from our last cos(h) meeting.

**Comment by martinjaeger** [comment]
@mikelovic @ben-talla:

Luckily I was just almost finished with the first draft of the energy management protocol specification. Just pushed it to this repository.

I will be very happy about any kind of feedback regarding the ideas :)
