### ISSUE TITLE
RFC: Rework CAN bus numbering and gateway forwarding

### ISSUE THREAD

**Issue by martinjaeger** [LibreSolar/thingset#25]
## Problem description

Currently there is only one bus number which identifies the physical CAN bus of the node that should receive a request. The same bus number is also used for the response.

This means that a gateway that connects two buses has to keep track of active forwarding "channels" and their addresses, which creates conflicts with CAN filters in the current design as explained below.

Example setup:

```
----------             ---------------              ----------
| Node A |   Bus 0x1   |   Gateway   |   Bus 0x2    | Node B |
|   0x0A |-------------| 0x10   0x20 |--------------| 0x0B   |
----------             ---------------              ----------
```

### Current design

The following messages are sent for a request from node A to B with a response from B to A.

```
Bus     CAN ID          Comment
---     ----------      -------------------------------------------
0x1     0x18020B0A      Node A addresses node B on bus 0x2
0x2     0x18020B20      Gateway uses its own source address
0x2     0x1802200B      Node B sends response back to gateway
0x1     0x18020A0B      Gateway translates source address back
```

As shown, the bus number is always the same and the gateway has to translate the source and target addresses.

The CAN stack of the gateway needs the following CAN RX filters on bus `0x02`:
- ID `0x18022000` with mask `0x1FFFFF00` for regular ISO-TP responses which are fed into the ISO-TP stack
- ID `0x1802200B` with mask `0x1FFFFFFF` for the channel to forward raw messages between node A and B

Both RX filters overlap. Depending on the hardware of the gateway, it will either receive a response frame to be forwarded (ID `0x1802200B`) in both filter callbacks (and confuse the ISO-TP stack) or it will receive the frame in only one filter callback, but it is not predictable which.

This means that the normal ISO-TP communication between the gateway and node B would have to be interrupted as soon as a forwarding channel is opened, which is not desirable.

### Proposed solution

Split the bus number into two 4-bit nibbles to identify target bus and source bus:

| Bits |     28 .. 26    |   25 .. 24  |  23 .. 20  |  19 .. 16  |   15 .. 8      |   7 .. 0       |
|------|:---------------:|:-----------:|:----------:|:----------:|:--------------:|:--------------:|
|      | Priority: `0x6` | Type: `0x0` | Target bus | Source bus | Target address | Source address |

With the proposed solution the above communication between node A and B would look like this:

```
Bus     CAN ID          Comment
---     ----------      -------------------------------------------
0x1     0x18210B0A      Node A addresses node B on bus 0x2
0x2     0x18210B0A      Gateway forwards the message transparently to bus 0x2
0x2     0x18120A0B      Node B sends response back to node A on bus 0x1
0x1     0x18120A0B      Gateway forwards the message transparently to bus 0x1
```

The gateway needs the following CAN RX filters on bus `0x01`:

- ID `0x18101000` with mask `0x1FF0FF00` for incoming ISO-TP messages
- ID `0x18200000` with mask `0x1FF00000` for forwarding raw messages from bus 1 to 2.

It is not possible for the gateway to have a generic filter for forwarding from bus `0x1` to any other bus (ID `0x18010000` with mask `0x1F0F0000`), as this would also match incoming ISO-TP messages for the gateway itself if the node on the other bus has the same node address as the gateway on bus `0x2`. This means that one filter per target bus is needed in every source bus CAN interface.

The gateway needs the following CAN RX filters on bus `0x02`:

- ID `0x18202000` with mask `0x1FF0FF00` for incoming ISO-TP messages
- ID `0x18100000` with mask `0x1FF00000` for forwarding raw messages from bus 2 to 1.

The node A needs the following CAN RX filter on bus `0x01`:

- ID `0x18100A00` with mask `0x1FF0FF00` for incoming ISO-TP messages

The node B needs the following CAN RX filter on bus `0x02`:

- ID `0x18200B00` with mask `0x1FF0FF00` for incoming ISO-TP messages

With this approach the IDs don't overlap anymore and the gateway does not need any processing of the messages to do the address translation anymore. In fact it can just set a filter for each bus combination it supports forwarding for (here 1 to 2 and vice versa) and forward without looking at the content of the messages.

**Comment by garethpotter** [comment]
I think this is sensible.

We have, of course, discussed this at length over other channels and explored other approaches. At the end of the day, this looks like the only solution that allows gateways to forward messages without maintaining any state (connection tracking, etc.).

Crucially, it also allows two nodes with the same node ID on different buses to talk to each other. Given:
```
----------             ---------------              ----------
| Node A |   Bus 0x1   |   Gateway   |   Bus 0x2    | Node B |
|   0x0A |-------------| 0x10   0x20 |--------------| 0x0A   |
----------             ---------------              ----------
```
- Node A listens with ID `0x18100A00` and mask `0x1FF0FF00` for incoming ISO-TP messages
- Node B listens with ID `0x18200A00` and mask `0x1FF0FF00` for incoming ISO-TP messages
- Node A sends messages to Node B using ID `0x18210A0A`
- Node B sends replies to Node A using ID `0x18120A0A`
