### ISSUE TITLE
RFC: Rework packetized reports

### ISSUE THREAD

**Issue by martinjaeger** [LibreSolar/thingset#28]
**IMPORTANT**: The reworked packetized reports had to be fixed once again after it was first merged based on the specs below. See #30 for further details.

## Problem description

A definition for packetized reports has been added in 06ee63a9134bfc822ef17fef19f3e6b990120a9a.

The following CAN frame layout is used:

| Bits | 28 .. 26 |  25 .. 24   |    23 .. 16          |   15 .. 8            |   7 .. 0       |
|------|:--------:|:-----------:|:--------------------:|:--------------------:|:--------------:|
|      | Priority | Type: `0x1` | Data object ID (MSB) | Data object ID (LSB) | Source address |

The first byte of the data section contains a sequence counter to make sure that no package is lost. The rest of the data is considered a stream of data where beginning and end of a message is determined similarly to the SLIP protocol (the same as for Bluetooth in the ThingSet specification).

We have discovered several shortcomings during testing of this approach:

**1. Not suitable for publishing record items**

Record items in binary mode (as shown in the new example in e4dbe99877ce54f7d31a96a740a05b2b82b7d6cd) identify the endpoint using the data object ID with an additional index (stored as a two-element array). With the current approach for packetized reports there is no way to store the index.

**2. Inefficient use of bytes in CAN ID**

One node cannot publish multiple reports in parallel anyway, so it is a waste of bandwidth to transfer the data object ID in every CAN frame even though only the first one would be sufficient.

**3. Packets cannot be routed to different buses.**

Only the source address is stored in the CAN ID, which means the message cannot be routed to a different bus like the request/response messages.

## Proposed solution 1

- Encode the sequence number in the CAN ID and remove the data object ID.
- Encode the source bus number in the CAN ID (similar to request/response messages).
- Use the data section to transfer full ThingSet reports (including the data object ID). This allows to send reports in any format, even in text mode. It also makes parsing much more simple and transparent.

The CAN frame layout would look like this:

| Bits | 28 .. 26 |  25 .. 24   |  23 .. 20  |  19 .. 16  |  15 .. 12  | 11 .. 8 |   7 .. 0       |
|------|:--------:|:-----------:|:----------:|:----------:|:----------:|:-------:|:--------------:|
|      | Priority | Type: `0x1` | res: `0x0` | Source bus | res: `0x0` | Seq.No  | Source address |

- The 4 bits used for target bus for request/response messages are unused and reserved for future additions.
- The sequence number is only 4 bits long instead of 8 bits, leaving another 4 bits for future use. CAN controller FIFOs usually can store around 3 CAN frames, so it is sufficient to have a (wrapping) sequence counter between 0 and 15 to detect lost frames.

## Proposed solution 2

Same as proposed solution 1, but with the following additions:

- Encode a 3-bit message number and an end flag (for last chunk) in bits 15 to 12. This allows get rid of the SLIP-like packetization algorithm for the payload and make the transfer even more simple and efficient.

The CAN frame layout would look like this:

| Bits | 28 .. 26 |  25 .. 24   |  23 .. 20  |  19 .. 16  | 15 .. 13 | 12  | 11 .. 8 |   7 .. 0       |
|------|:--------:|:-----------:|:----------:|:----------:|:--------:|:---:|:-------:|:--------------:|
|      | Priority | Type: `0x1` | res: `0x0` | Source bus | Msg no.  | End | Seq no. | Source address |

The message number is a wrapping counter from 0 to 7. Each message starts with a new sequence (sequence number set to 0). The sequence number is also wrapping, so there is no maximum message length. The final frame for one message sets the end flag to 1, otherwise it is set to 0. This way any lost CAN frames can be detected and the CAN ID is used very efficiently.

The approach is similar to the NMEA-2000 Fast Packet transport with the difference that this solution does not encode the length of an entire message. Instead, the end of a message is indicated with the end flag. If receiving devices don't have a sufficiently large buffer they will not know in advance, but must just skip additional messages as soon as the buffer is full and the final frame has not been received, yet.

## Impact

The definition for packetized reports has been added to the v0.6 spec. There are no more type bits available in the CAN ID, which means that the new approach cannot be added in addition to the existing packetized reports. This means it would be a breaking change, incompatible with existing devices.

As the implementation has not been around for a long time, I still suggest to take that step right now. The specification document contains a warning that the CAN definitions are still preliminary.

CC @garethpotter @pasrom

**Comment by garethpotter** [comment]
I like this. To summarise my understanding:
* Type `0x01` reports would become the preferred default for any device using CAN-FD:
  * Easier and simpler to parse in client code
  * Records, etc. supported
* Type `0x02` reports remain available and are an efficient option for classical CAN devices

**Comment by martinjaeger** [comment]
Yes, and type `0x2` reports may still be more suitable for some control purposes, as it allows to filter for a specific data object ID (or range of IDs) in hardware.

**Comment by martinjaeger** [comment]
@garethpotter I've updated the RFC and added a second solution proposal, which is better and more efficient in my opinion. If there are no objections, I'll go ahead with implementation according to solution 2.
